### ISSUE TITLE
[getOnlinePlayers] NoSuchMethodError

### ISSUE THREAD

**Issue by Flodding** [m0r13/MapTools#4]
Im getting following error when starting minecraft with this plugin:

`[19:59:46] [Server thread/INFO]: [MapTools] Loading MapTools v0.1`

`[19:59:55] [Server thread/WARN]: [MapTools] Task #5 for MapTools v0.1 generated an exception
java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOnlinePlayers()[Lorg/bukkit/entity/Player;
	at me.m0r13.maptools.MarkerUpdateTask.run(MarkerUpdateTask.java:45) ~[?:?]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[minecraft_server.jar:git-Spigot-f04e043-52c7fc0]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [minecraft_server.jar:git-Spigot-f04e043-52c7fc0]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729) [minecraft_server.jar:git-Spigot-f04e043-52c7fc0]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [minecraft_server.jar:git-Spigot-f04e043-52c7fc0]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [minecraft_server.jar:git-Spigot-f04e043-52c7fc0]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [minecraft_server.jar:git-Spigot-f04e043-52c7fc0]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
`

**Comment by elamperti** [comment]
@Flodding update your MapTools and it should fix it, as the Spigot API changed somewhere around Sep/2015. If it doesn't work, try modifying the Spigot API version in `pom.xml` as in PR #5 and compile again (you'll need maven and openjdk-7-jdk) running the following command from the project folder:

    mvn clean install

The resulting jar will be located under `./target/maptools-0.0.1-SNAPSHOT.jar`
Hope this helps you :)
