### ISSUE TITLE
NoSuchMethodError in Spigot 1.13.2

### ISSUE THREAD

**Issue by wesleyegbertsen** [m0r13/MapTools#7]
I am getting the following errors in my console running Spigot 1.13.2:

```
[21:28:21 WARN]: [MapTools] Task #2 for MapTools v0.1 generated an exception
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
        at me.m0r13.maptools.MarkerUpdateTask.run(Unknown Source) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:391) [spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar:git-Spigot-a1f2566-97b0057]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

```

**Comment by wesleyegbertsen** [comment]
It seems to be that newer api returns a Collection<Player> instead of an array.

**Comment by wesleyegbertsen** [comment]
I seemed to have fix it by updating the api version in the pom.xml. Now there is still a exception on stopping the server:

```
[21:57:24 ERROR]: Error occurred while disabling MapTools v0.1 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
```

Seems to happen in the disablePlugin call, will check if I can fix this.

**Comment by wesleyegbertsen** [comment]
Fixed the plugin, it now support 1.13.2. Also the exception that would occur when stopping the server is gone. See pull request: https://github.com/m0r13/MapTools/pull/8
